### ISSUE TITLE
Push to Dockerhub

### ISSUE THREAD

**Issue by strarsis** [j-a-m-l/jewellery.rb#1]
Would it be possible to push this on Dockerhub, 
it doesn't has to be the official geminabox image, 
just having the possibility of pulling it without building it first.

**Comment by j-a-m-l** [comment]
I just did it. Try it now if you want.

**Comment by strarsis** [comment]
Awesome!
What dockerhub user + repo is used?
I tried to find it by the Github repo name, but it doesn't seem to have the same name.
It may be helpful to add the docker pull command to the README.

**Comment by j-a-m-l** [comment]
Thank you @strarsis for your suggestion. I just added the image repo URL.

**Comment by strarsis** [comment]
It may be necessary that you have to push the first image.

```
$ docker pull jaml/jewellery.rb
Using default tag: latest
Pulling repository docker.io/jaml/jewellery.rb
Tag latest not found in repository docker.io/jaml/jewellery.rb
```

This dockerhub feature can spare the manual building each time:
https://docs.docker.com/docker-hub/builds/
